export {setConfigData} from '@redux/slices/config';
export {setUserData} from '@redux/slices/user';
export {setWithdrawData} from '@redux/slices/withdraw';
export {setProductData} from '@redux/slices/product';
export {setOrderData} from '@redux/slices/order';
export {setTransactionData} from '@redux/slices/transaction';
export {setSlideData} from '@redux/slices/slide';
export {setInvestmentData} from '@redux/slices/investment';
export {setNotificationData} from '@redux/slices/notification';
